[package]
name = "gg-render-native"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-render = { workspace = true }
image = { workspace = true }
ab_glyph = { workspace = true }
softbuffer = { workspace = true }
tiny-skia = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = { workspace = true }
pollster = { workspace = true }
