[package]
name = "gg-runtime-audio"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
cpal = { workspace = true, optional = true }
rodio = { workspace = true, optional = true }

[features]
default = []
cpal-backend = ["dep:cpal", "dep:rodio"]
