[package]
name = "gg-compiler-aot"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-bytecode = { workspace = true }
cranelift = "0.112"
cranelift-module = "0.112"
cranelift-object = "0.112"
cranelift-codegen = "0.112"
target-lexicon = "0.12"
