[package]
name = "gg-tools"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[[bin]]
name = "gg"
path = "bin/gg.rs"

[dependencies]
gg-core = { workspace = true }
gg-manifest = { workspace = true }
gg-factory = { workspace = true }
gg-script = { workspace = true }
gg-vm = { workspace = true }
gg-runtime-core = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
