[package]
name = "gg-shader"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
naga = { workspace = true }
indexmap = { workspace = true }
gg-core = { workspace = true }
oak-core = { workspace = true }
oak-valkyrie = { workspace = true }
