[package]
name = "gg-shader"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[features]
default = []
valkyrie-compiler = ["oak-core", "oak-valkyrie"]

[dependencies]
gg-core = { workspace = true }
naga = { workspace = true }
indexmap = { workspace = true }
oak-core = { workspace = true, optional = true }
oak-valkyrie = { workspace = true, optional = true }
