[workspace]
members = [
    "projects/core/*",
    "projects/runtime/*",
    "projects/compiler/gg-script",
    "projects/plugins/*",
    "examples/basic",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
gg-core = { path = "projects/core/gg-core" }
gg-ecs = { path = "projects/core/gg-ecs" }
gg-asset = { path = "projects/core/gg-asset" }
gg-render = { path = "projects/core/gg-render" }
gg-runtime-core = { path = "projects/runtime/gg-runtime-core" }
gg-ir = { path = "projects/runtime/gg-ir" }
gg-vm = { path = "projects/runtime/gg-vm" }
gg-script = { path = "projects/compiler/gg-script" }
serde = { version = "1", features = ["derive"] }