[package]
name = "gg-render-wgpu"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-render = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
image = { workspace = true }
ab_glyph = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
