[package]
name = "gg-plugin-portrait"
version = "0.1.0"
edition = "2021"

[dependencies]
gg-core = { path = "../../core/gg-core" }
gg-ecs = { path = "../../core/gg-ecs" }
gg-asset = { path = "../../core/gg-asset" }
gg-galgame-schema = { path = "../gg-galgame-schema" }
gg-render = { workspace = true }
