[package]
name = "gg-plugin-tilemap"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-render = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
