[package]
name = "gg-galgame-schema"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-asset = { workspace = true }
gg-manifest = { workspace = true }
serde = { workspace = true }
