[package]
name = "gg-mcp"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-manifest = { workspace = true }
gg-lsp = { workspace = true }
oak-vfs = { workspace = true }
oak-mcp = { workspace = true, features = ["io-std"] }
tokio = { workspace = true }

[features]
default = []
lsp = ["gg-lsp/lsp"]
