[package]
name = "gg-engine-platformer"
description = "Platformer (2D platform) game engine based on GG meta-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
gg-core = { path = "../../core/gg-core" }
gg-ecs = { path = "../../core/gg-ecs" }
gg-asset = { path = "../../core/gg-asset" }
gg-render = { path = "../../core/gg-render" }
gg-render-wgpu = { path = "../../runtime/gg-render-wgpu" }
gg-ui = { path = "../../plugins/gg-ui" }
gg-platform-desktop = { path = "../../platforms/gg-platform-desktop" }
