[package]
name = "gg-compiler-asset"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[features]
default = ["full-compilers"]
full-compilers = ["gg-schema", "gg-script", "gg-compiler-shader", "gg-compiler-widget"]

[dependencies]
gg-core = { workspace = true }
gg-compiler = { workspace = true }
gg-meta = { workspace = true }
gg-schema = { workspace = true, optional = true }
gg-script = { workspace = true, optional = true }
gg-compiler-shader = { workspace = true, optional = true }
gg-compiler-widget = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
toml = { workspace = true }
