[package]
name = "sync-dev"
version = "0.1.0"
edition = "2021"
description = "GWG Engine 同步开发工具"
license = "MIT"

[dependencies]
gwg-agent = { path = "../../frameworks/gwg-agent", version = "0.1.0" }
gwg-dependency = { path = "../../frameworks/gwg-dependency", version = "0.1.0" }
gwg-verification = { path = "../../frameworks/gwg-verification", version = "0.1.0" }
clap = { version = "2.33.3", features = ["yaml"] }
thiserror = { workspace = true }