[package]
name = "gg-plugin-scene-transition"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-asset = { workspace = true }
gg-render = { workspace = true }
gg-plugin-dialogue = { workspace = true }
