[package]
name = "gwg-world"
version = "0.1.0"
edition = "2021"
description = "GWG Engine 世界管理"
license = "MIT"

[dependencies]
gwg-ecs = { path = "../gwg-ecs", version = "0.1.0" }
gwg-asset = { path = "../gwg-asset", version = "0.1.0" }
gwg-reflection = { path = "../gwg-reflection", version = "0.1.0" }
