[package]
name = "gg-galgame"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-asset = { workspace = true }
gg-plugin-dialogue = { workspace = true }
gg-plugin-portrait = { workspace = true }
gg-plugin-scene-transition = { workspace = true }
gg-plugin-save = { workspace = true }
gg-plugin-ui = { workspace = true }
gg-render = { workspace = true }
gg-render-wgpu = { workspace = true }
gg-ui = { workspace = true }
winit = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
image = { workspace = true }
gg-manifest = { workspace = true }
