[package]
name = "gg-runtime-core"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-asset = { workspace = true }
gg-render = { workspace = true }
gg-script = { workspace = true }
gg-ir = { workspace = true }
gg-bytecode = { workspace = true }
gg-vm = { workspace = true }
gg-runtime-audio = { workspace = true }
gg-platform-desktop = { workspace = true }
