[package]
name = "gg-editor-inspector"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-galgame-schema = { workspace = true }
gg-editor-shell = { workspace = true }
gg-ui = { workspace = true }
