[package]
name = "gg-editor-shell"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-world = { workspace = true }
gg-render = { workspace = true }
gg-editor-render = { workspace = true }
gg-ui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
winit = { workspace = true }
libloading = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = { workspace = true }

[dev-dependencies]
gg-world = { workspace = true }
