[package]
name = "gg-editor-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-world = { workspace = true }
gg-render = { workspace = true }
gg-editor-render = { workspace = true }
gg-ui = { workspace = true }
winit = { workspace = true }
