[package]
name = "gg-platform-ios"
version.workspace = true
description = "GG 引擎 iOS 平台实现"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
gg-core.workspace = true
gg-platform.workspace = true

[dev-dependencies]
tokio = { version = "1.51.1", features = ["full"] }
