[package]
name = "gg-ui"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-error = { workspace = true }
gg-render = { workspace = true }
oak-voc = { workspace = true }
num_cpus = { workspace = true }
ab_glyph = { workspace = true }
