[package]
name = "gg-engine-stg"
description = "STG (Shoot 'em up) game engine based on GG meta-engine"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-core = { workspace = true }
gg-ecs = { workspace = true }
gg-asset = { workspace = true }
gg-render = { workspace = true }
gg-render-wgpu = { workspace = true }
gg-ui = { workspace = true }
gg-platform-desktop = { workspace = true }
