[package]
name = "gg-game-ui"
version = "0.1.0"
edition = "2021"
description = "GG Game UI system based on GameObject and Component"
license = "MIT"

[dependencies]
gg-ecs = { path = "../../core/gg-ecs" }
gg-error = { path = "../../core/gg-error" }
gg-render = { path = "../../core/gg-render" }

[features]
default = []
