[package]
name = "gg-game-ui"
version = { workspace = true }
edition = { workspace = true }
description = "GG Game UI system based on GameObject and Component"
authors = { workspace = true }
license = { workspace = true }

[dependencies]
gg-ecs = { workspace = true }
gg-error = { workspace = true }
gg-render = { workspace = true }

[features]
default = []
